# This file was generated by GoReleaser. DO NOT EDIT.
class Metaq < Formula
  desc "metaq propagates the same query on multiple databases on the same engine"
  homepage "https://github.com/LemontechSA/metaq"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/LemontechSA/metaq/releases/download/v0.1.1/metaq_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "b0bfcc74babe258a6469d86a9335768de23e8d30837e3d6cd1866d7156893f0f"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/LemontechSA/metaq/releases/download/v0.1.1/metaq_0.1.1_Linux_x86_64.tar.gz"
    sha256 "6d9eadfe30aa2f1dbca5147f3c549a54c300dfd03b62520adf03d0e589fef4a4"
  end

  def install
    bin.install "metaq"
  end
end
